webserver:
  host: !ENV ${WEBSERVER_HOST}
  port: !ENV ${WEBSERVER_PORT}

db:
  connection_string: !ENV ${DB_CONNECTION_STRING}

jwt:
  secret_key: !ENV ${JWT_SECRET_KEY}
  algorithm: !ENV ${JWT_ALGORITHM}
  token_expire_mins: !ENV ${JWT_TOKEN_EXPIRE_MINS}

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      (): "uvicorn.logging.DefaultFormatter"
      fmt: "%(asctime)s %(levelname)s - %(name)s %(module)s - %(funcName)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    access:
      (): "uvicorn.logging.AccessFormatter"
      fmt: '%(asctime)s %(levelname)s - %(name)s: %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    default:
      formatter: "default"
      class: "logging.StreamHandler"
      stream: "ext://sys.stderr"
    access:
      formatter: "access"
      class: "logging.StreamHandler"
      stream: "ext://sys.stdout"
  loggers:
    "":
      handlers:
        - "default"
      level: "INFO"
    uvicorn.error:
      level: INFO
    uvicorn.access:
      handlers:
        - "access"
      level: "INFO"
      propagate: True
    engineio.server:
      level: "ERROR"
    azure.storage.common.storageclient:
      level: "ERROR"
